name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: ci
    uses: Spryx-AI/spryx-devops-workflows/.github/workflows/spryx-pypi-publish.yml@main
    with:
      python-version: "3.12"         # Optional, Python version to use (default: "3.12")
      publish-to-testpypi: false     # Optional, also publish to TestPyPI (default: false)
      check-description: true        # Optional, validate package description (default: true)
    secrets:
      pypi-token: ${{ secrets.PYPI_TOKEN }}